<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.pager.testcases.ChatAppTest" tests="4" time="4.034" ignored="0" failures="1" timestamp="31 May 2021 08:31:28 GMT" skipped="0" hostname="JESS-DELL-LAPTOP-PNJ8QBL" errors="0">
  <testcase name="joinChat" time="1.340" classname="com.pager.testcases.ChatAppTest"/>
  <testcase name="signoutOfChat" time="0.505" classname="com.pager.testcases.ChatAppTest">
    <failure type="java.lang.AssertionError" message="Signout url not verified -Actual: https://pager-qa-hiring.herokuapp.com/#/chat -Excpected to contain:  signout expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Signout url not verified -Actual: https://pager-qa-hiring.herokuapp.com/#/chat -Excpected to contain:  signout expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.pager.utility.Helper.VerifyPartialText(Helper.java:65)
	at com.pager.testcases.ChatAppTest.signoutOfChat(ChatAppTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- signoutOfChat -->
  <testcase name="chatLoads" time="0.543" classname="com.pager.testcases.ChatAppTest"/>
  <testcase name="sendAMessage" time="1.646" classname="com.pager.testcases.ChatAppTest"/>
</testsuite> <!-- com.pager.testcases.ChatAppTest -->
